scraping_management/urls.py
from django.urls import path
from . import views,api_views
app_name = 'scraping_management'
urlpatterns = [
    path('',views.GestionarEjecuciones,name='dashboard'),
    #path('api/all_ofertas/',api_views.all_ofertas,name='all_ofertas'),
    path('api/all_ofertas/',api_views.AllOfertas.as_view(),name='all_ofertas'),
    path('api/first_oferta_api',api_views.first_oferta_api),
    path('probar_parametros/resultados_prueba/<int:pk>',views.resultados_prueba_view,name='resultados_prueba'),
    path('ejecuciones/',views.EjecucionListView.as_view(),name='ejecuciones_list'),
    path('sitios_web/',views.SitioWebListView.as_view(),name='sitios_web_list'),
    path('ofertas_list/<int:pk>',views.OfertasListView.as_view(),name='ofertas_list'),
    path('parametros_edit/<int:pk>',views.parametros_form,name='ejecucion_parametro_edit'),
    path('ejecutar/<int:pk>',views.ejecutar,name='ejecutar'),
    path('crear_ejecucion/',views.CrearEjecucionView.as_view(),name='crear_ejecucion'),
    path('crear_sitio_web/',views.CrearSitioWebView.as_view(),name='crear_sitio_web'),
    path('entry_success',views.FormSuccessView.as_view(),name='entry_success'),
    path('probar_parametros/',views.probar_parametros,name='probar_parametros'),

]

sistemawebscraping/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('scraping_management.urls')),

]

scraping_management/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=70)

    class Meta:
        db_table = 'categoria'

    def __str__(self):
        return self.nombre

class Caracteristica(models.Model):
    nombre = models.CharField(max_length=30)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    class Meta:
        db_table = 'caracteristica'
    def __str__(self):
        return self.nombre

class Spider(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=70)
    es_produccion = models.BooleanField()
    class Meta:
        db_table = 'spider'
    def __str__(self):
        return self.nombre

class Parametro(models.Model):
    nombre = models.CharField(max_length=15)
    descripcion = models.CharField(max_length=70)
    spider = models.ForeignKey(Spider,on_delete=models.CASCADE)
    class Meta:
        db_table = 'parametro'
    def __str__(self):
        return self.nombre


class SitioWeb(models.Model):
    """El sitio web de donde se extraen los datos"""
    dominio = models.URLField(max_length=50)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=70)
    empresa = models.CharField(max_length=50)
    habilitado = models.BooleanField(default=True)

    class Meta:
        db_table = 'sitiweb'
    def __str__(self):
        return self.nombre

class SitioWebParametro(models.Model):
    sitio_web = models.ForeignKey(SitioWeb,on_delete=models.CASCADE)
    parametro = models.ForeignKey(Parametro,on_delete=models.CASCADE)
    valor_parametro = models.CharField(max_length=150)

    class Meta:
        db_table = 'ejecucionparametro'
    def __str__(self):
        return  f'{self.ejecucion} {self.parametro} {self.valor_parametro}'

class Ejecucion(models.Model):
    sitio_web = models.ForeignKey(SitioWeb,null=True,on_delete=models.SET_NULL)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE,null=True)
    spider = models.ForeignKey(Spider,on_delete=models.CASCADE)
    parametros = models.ManyToManyField('Parametro',through='EjecucionParametro')

    class Meta:
        db_table = 'ejecucion'
    def __str__(self):
        return f'{self.sitio_web} {self.categoria}'

class EjecucionParametro(models.Model):
    ejecucion = models.ForeignKey(Ejecucion,on_delete=models.CASCADE)
    parametro = models.ForeignKey(Parametro,on_delete=models.CASCADE)
    valor_parametro = models.CharField(max_length=100)

    def __str__(self):
        return  f'{self.ejecucion} {self.parametro} {self.valor_parametro}'

class Oferta(models.Model):
    titulo = models.CharField(max_length=250)
    precio = models.FloatField()
    divisa =models.CharField(max_length=10)
    fecha_extraccion = models.DateTimeField()
    ejecucion = models.ForeignKey(Ejecucion,null=True,on_delete=models.SET_NULL)
    url_image = models.CharField(max_length=1000)

    class Meta:
        db_table = 'oferta'

    def __str__(self):
        return f'{self.fecha_extraccion,self.titulo}'

scraping_management/forms.py
from django import forms
from .models import Ejecucion,Spider
class SpiderForm(forms.Form):
    spider = forms.ModelChoiceField(queryset=Spider.objects.all())

scraping_management/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.views import View
from django.views.generic import ListView,TemplateView
from django.views.generic.edit import CreateView
from django.forms import modelformset_factory,TextInput
from .models import Ejecucion,EjecucionParametro,SitioWeb,Spider,Parametro,Oferta
from .forms import SpiderForm
from .services import request_parameters_generator
import requests

class EjecucionListView(ListView):
    model = Ejecucion
    context_object_name = 'ejecuciones'
    paginate_by = 30
    template_name = 'scraping_management/extractores.html'

class OfertasListView(ListView):
    model = Oferta
    context_object_name = 'ofertas'
    paginate_by = 100
    template_name = 'scraping_management/ofertas.html'

    def get_queryset(self):
        sitio_web = SitioWeb.objects.get(pk=self.kwargs['pk'])
        ejecuciones = sitio_web.ejecucion_set.all()
        p = Oferta.objects.none()
        for ejecucion in ejecuciones:
            ofertas = ejecucion.oferta_set.all()
            p = p.union(p,ofertas)

        return p


class SitioWebListView(ListView):
    model = SitioWeb
    context_object_name = 'sitios_web'
    paginate_by = 20
    template_name = 'scraping_management/sitios_web.html'


class CrearEjecucionView(CreateView):
    model = Ejecucion
    fields = ['sitio_web','categoria','spider']
    template_name = 'scraping_management/create_records.html'
    success_url = '/dashboard/entry_success'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de Ejecucion'
        return context


class CrearSitioWebView(CreateView):
    model = SitioWeb
    fields = ['nombre','dominio','descripcion','empresa']
    template_name = 'scraping_management/create_records.html'
    success_url = '/dashboard/entry_success'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de Sitio Web'
        return context

class FormSuccessView(View):
    def get(self, request, *args, **kwargs):
        messages.success(request,'Registro creado correctamente')
        return render(request,'scraping_management/mensajes.html')

def GestionarEjecuciones(request):
    return render(request,'scraping_management/extractores.html')

def ejecutar(request,pk):
    ejecucion = get_object_or_404(Ejecucion,pk=pk)
    if request.method == 'GET':
        if ejecucion.parametros.all().exists() == False:
            messages.error(request, 'Antes de ejecutar primero debe ingresar los parametros')
        else:
            url = 'http://localhost:6800/schedule.json'
            data = request_parameters_generator(ejecucion,True)
            #print(data)
            response = requests.post(url, data=data)
            json_response = response.json()
            if json_response['status'] == 'ok':
                messages.success(request, f'Ejecucion exitosa,jobid:{json_response["jobid"]}')
            else:
                messages.error(request, f'Fallo en la ejecucion:{json_response["message"]}')


        return render(request,'scraping_management/mensajes.html')




def parametros_form(request,pk):
    ejecucion = get_object_or_404(Ejecucion,pk=pk)
    EjecucionParametroFormSet = modelformset_factory(EjecucionParametro,fields=('valor_parametro',),extra=0,widgets={'valor_parametro':TextInput(attrs={'size':50})})
    if ejecucion.parametros.all().exists() == False:
        parametros = ejecucion.spider.parametro_set.all()
        ejecucion.parametros.add(*parametros)

    queryset = ejecucion.ejecucionparametro_set.all()
    if request.method == 'POST':
        formset = EjecucionParametroFormSet(request.POST,queryset=queryset)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Parametros actualizados correctamente')
    else:
        formset = EjecucionParametroFormSet(queryset=queryset)

    return render(request,'scraping_management/parametros_edit.html',{'formset':formset,'id':pk})

def resultados_prueba_view(request,pk):
    ejecucion = get_object_or_404(Ejecucion, pk=pk)
    if request.method == 'GET':
        data = request_parameters_generator(ejecucion, False)
        url = 'http://localhost:9080/crawl.json?'
        response = requests.get(url, params=data)
        json_response = response.json()
        items_list=[]
        if json_response['status'] == 'ok':
            if 'errors' in json_response:
                messages.error(request, f'Fallo en la ejecucion:{json_response["message"]}')
                return render(request, 'scraping_management/resultados_prueba.html',
                              {'items': '', 'keys': '', 'items_count': 0})
            else:
                for i in range(len(json_response['items'])):
                    items_list.append(json_response['items'][i])

                item_keys = []
                items_count = json_response['stats']['item_scraped_count']
                for key in items_list[0].keys():
                    item_keys.append(key)

                return render(request, 'scraping_management/resultados_prueba.html',
                              {'items': items_list, 'keys': item_keys, 'items_count': items_count})

        else:
            messages.error(request, f'Fallo en la ejecucion:{json_response["message"]}')

    return render(request,'scraping_management/resultados_prueba.html')



def probar_parametros(request):
    if request.method == 'POST':
        ProbarParametroFormSet = modelformset_factory(EjecucionParametro, fields=('valor_parametro',), extra=0)
        if 'parametros_form' in request.POST:
            print('es parametro')
            spider_form = SpiderForm(request.POST)
            probar_parametros_form = ProbarParametroFormSet(request.POST)
            if probar_parametros_form.is_valid():
                probar_parametros_form.save()
                return redirect(f'resultados_prueba/{probar_parametros_form[0].instance.ejecucion.pk}')

        if 'spider_selected' in request.POST:
            spider_form = SpiderForm(request.POST)
            if spider_form.is_valid():
                spider = Spider.objects.get(pk=spider_form.cleaned_data['spider'].pk)
                ejecucion = Ejecucion(spider=spider)
                ejecucion.save()
                parametros = spider.parametro_set.all()
                ejecucion.parametros.add(*parametros)
                ejecucion_parametro = ejecucion.ejecucionparametro_set.all()
                probar_parametros_form = ProbarParametroFormSet(queryset=ejecucion_parametro)
                print('es spider')

    else:
        spider_form = SpiderForm()
        probar_parametros_form = None

    return render(request,'scraping_management/probar_parametros.html',{'spider_form':spider_form,'probar_parametros_form':probar_parametros_form})

scraping_management/templates/scraping_management/create_records.html
{% extends 'base.html' %}
{% block content %}
<h3 class="text-dark mb-4">{{ titulo }}</h3>
 <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Guardar" />
 </form>
{% endblock %}

scraping_management/templates/scraping_management/extractores.html
{% extends 'base.html' %}
{% block content%}

 <div class="container-fluid">
                    <h3 class="text-dark mb-4">Ejecuciones</h3>
                    <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Lista de Ejecuciones</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length-1" class="dataTables_length" aria-controls="dataTable"><label class="form-label" style="margin: 0px;margin-right: 66px;">Show&nbsp;<select class="d-inline-block form-select form-select-sm">
                                                <option value="10" selected="">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                            </select>&nbsp;</label><a class="btn btn-primary" href="{% url 'scraping_management:crear_ejecucion' %}">Crear Ejecucion</a></div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-end dataTables_filter" id="dataTable_filter"><label class="form-label"><input type="search" class="form-control form-control-sm" aria-controls="dataTable" placeholder="Search"></label></div>
                                </div>
                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th style="width: 60.2px;">Id</th>
                                            <th>Sitio Web</th>
                                            <th>Categoria</th>
                                            <th>Spider</th>
                                            <th>Programacion</th>
                                            <th>Parametros</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for ejecucion in ejecuciones %}
                                        <tr>
                                            <td>{{ ejecucion.id }}</td>
                                            <td>{{ ejecucion.sitio_web }}</td>
                                            <td>{{ ejecucion.categoria }}</td>
                                            <td>{{ ejecucion.spider }}</td>
                                            <td>Ejecucion cada N horas</td>
                                            <td>
                                                 <a class="btn btn-primary btn-info" href="/dashboard/parametros_edit/{{ejecucion.id}}">Parametros</a>

                                            </td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <a class="btn btn-primary" href="/parametros_edit/{{ejecucion.id}}"><i class="far fa-calendar-alt"></i></a>
                                                    <button class="btn btn-primary btn-secondary" type="button"><i class="fas fa-edit"></i></button>
                                                    <a class="btn btn-primary btn-success" href="/dashboard/ejecutar/{{ejecucion.id}}"><i class="fas fa-play"></i></a>

                                                    <button class="btn btn-primary btn-danger" type="button"><i class="fas fa-trash-alt"></i></button>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}


                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to 10 of 27</p>
                                </div>
                                <div class="col-md-6">
                                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                        <ul class="pagination">
                                            <li class="page-item disabled"><a class="page-link" aria-label="Previous" href="#"><span aria-hidden="true">«</span></a></li>
                                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                                            <li class="page-item"><a class="page-link" aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
 </div>

{% endblock %}

scraping_management/templates/scraping_management/mensajes.html
{% extends 'base.html' %}
{% block content %}
<div class=" d-md-inline ">
        <a class="btn rounded-circle bg-info border-5 mb-1"  href="/dashboard/ejecuciones"><i class="fas fa-chevron-left"></i></a>
</div>
{% for message in messages %}
    <div class="alert alert-{% if message.level_tag   == 'error' %}danger{% else %}{{message.level_tag }}{% endif %}"
    role="alert">
      {{ message }}
    </div>
{% endfor %}
{{ mensaje }}
{% endblock %}

scraping_management/templates/scraping_management/ofertas.html
{% extends 'base.html' %}
{% block content%}

 <div class="container-fluid">
                    <h3 class="text-dark mb-4">Ofertas</h3>
                    <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Lista de Ofertas</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length-1" class="dataTables_length" aria-controls="dataTable"><label class="form-label" style="margin: 0px;margin-right: 66px;">Show&nbsp;<select class="d-inline-block form-select form-select-sm">
                                                <option value="10" selected="">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                            </select>&nbsp;</label>
                                        {{ofertas|length}} ofertas
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-end dataTables_filter" id="dataTable_filter"><label class="form-label"><input type="search" class="form-control form-control-sm" aria-controls="dataTable" placeholder="Search"> </label></div>

                                </div>
                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th style="width: 60.2px;">Id</th>
                                            <th>Titulo</th>
                                            <th>Precio</th>
                                            <th>Divisa</th>
                                            <th>Fecha de Extraccion</th>
                                            <th>Ejecucion</th>
                                            <th>Url imagen de oferta</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for oferta in ofertas %}
                                        <tr>
                                            <td>{{ oferta.id }}</td>
                                            <td>{{ oferta.titulo }}</td>
                                            <td>{{ oferta.precio }}</td>
                                            <td>{{ oferta.divisa }}</td>
                                            <td>{{ oferta.fecha_extraccion }}</td>
                                            <td>{{ oferta.ejecucion_id }}</td>
                                            <td>{{ oferta.url_image }}</td>
                                        </tr>
                                    {% endfor %}


                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to 10 of 27</p>
                                </div>
                                <div class="col-md-6">
                                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                        <ul class="pagination">
                                            <li class="page-item disabled"><a class="page-link" aria-label="Previous" href="#"><span aria-hidden="true">«</span></a></li>
                                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                                            <li class="page-item"><a class="page-link" aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
 </div>

{% endblock %}

scraping_management/templates/scraping_management/resultados_prueba.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
                    <h3 class="text-dark mb-4">Resultados de la prueba </h3>
                    <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Items extraido con los parametros probados:</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length-1" class="dataTables_length" aria-controls="dataTable">
                                        <label class="form-label" style="margin: 0px;margin-right: 66px;">{{ items_count }} items extraidos</label><a class="btn btn-primary" href="{% url 'scraping_management:crear_ejecucion' %}">Guardar como ejecucion</a>
                                    </div>
                                </div>

                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            {% for key in keys %}
                                            <th>{{key}}</th>
                                            {% endfor %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in items%}
                                        <tr>
                                            {% for key,value in item.items %}
                                            <td>{{ value}}</td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}


                                </table>
                            </div>

                        </div>
                    </div>
 </div>

{% endblock %}

scraping_management/templates/scraping_management/sitios_web.html
{% extends 'base.html' %}
{% block content%}

 <div class="container-fluid">
                    <h3 class="text-dark mb-4">Sitios Web</h3>
                    <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Lista de Sitios Web</p>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 text-nowrap">
                                    <div id="dataTable_length-1" class="dataTables_length" aria-controls="dataTable"><label class="form-label" style="margin: 0px;margin-right: 66px;">Show&nbsp;<select class="d-inline-block form-select form-select-sm">
                                                <option value="10" selected="">10</option>
                                                <option value="25">25</option>
                                                <option value="50">50</option>
                                                <option value="100">100</option>
                                            </select>&nbsp;</label><a class="btn btn-primary" href="{% url 'scraping_management:crear_sitio_web' %}">Crear Sitio Web</a></div>
                                </div>
                                <div class="col-md-6">
                                    <div class="text-md-end dataTables_filter" id="dataTable_filter"><label class="form-label"><input type="search" class="form-control form-control-sm" aria-controls="dataTable" placeholder="Search"></label></div>
                                </div>
                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                                    <thead>
                                        <tr>
                                            <th style="width: 60.2px;">Id</th>
                                            <th>Nombre</th>
                                            <th>Dominio</th>
                                            <th>Descripcion</th>
                                            <th>Empresa</th>
                                            <th>Cantidad de ofertas</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for sitio_web in sitios_web %}
                                        <tr>
                                            <td>{{ sitio_web.id }}</td>
                                            <td>{{ sitio_web.nombre }}</td>
                                            <td>{{ sitio_web.dominio }}</td>
                                            <td>{{ sitio_web.descripcion }}</td>
                                            <td>{{ sitio_web.empresa }}</td>
                                            <td>500 ofertas</td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <a class="btn btn-primary" href="/dashboard/ofertas_list/{{sitio_web.id}}"><i class="far fa-calendar-alt"></i></a>
                                                    <button class="btn btn-primary btn-secondary" type="button"><i class="fas fa-edit"></i></button>
                                                    <a class="btn btn-primary btn-success" href="/dashboard/ejecutar/"><i class="fas fa-play"></i></a>

                                                    <button class="btn btn-primary btn-danger" type="button"><i class="fas fa-trash-alt"></i></button>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}


                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Showing 1 to 10 of 27</p>
                                </div>
                                <div class="col-md-6">
                                    <nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
                                        <ul class="pagination">
                                            <li class="page-item disabled"><a class="page-link" aria-label="Previous" href="#"><span aria-hidden="true">«</span></a></li>
                                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                                            <li class="page-item"><a class="page-link" aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
 </div>

{% endblock %}