scraping_management/urls.py
from django.urls import path
from . import views,api_views
app_name = 'scraping_management'
urlpatterns = [
    path('',views.GestionarEjecuciones,name='dashboard'),
    #path('api/all_ofertas/',api_views.all_ofertas,name='all_ofertas'),
    path('api/all_ofertas/',api_views.AllOfertas.as_view(),name='all_ofertas'),
    path('api/first_oferta_api',api_views.first_oferta_api),
    path('probar_parametros/resultados_prueba/<int:pk>',views.resultados_prueba_view,name='resultados_prueba'),
    path('ejecuciones/',views.EjecucionListView.as_view(),name='ejecuciones_list'),
    path('sitios_web/',views.SitioWebListView.as_view(),name='sitios_web_list'),
    path('ofertas_list/<int:pk>',views.OfertasListView.as_view(),name='ofertas_list'),
    path('parametros_edit/<int:pk>',views.parametros_form,name='ejecucion_parametro_edit'),
    path('ejecutar/<int:pk>',views.ejecutar,name='ejecutar'),
    path('crear_ejecucion/',views.CrearEjecucionView.as_view(),name='crear_ejecucion'),
    path('crear_sitio_web/',views.CrearSitioWebView.as_view(),name='crear_sitio_web'),
    path('entry_success',views.FormSuccessView.as_view(),name='entry_success'),
    path('probar_parametros/',views.probar_parametros,name='probar_parametros'),

]

sistemawebscraping/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('scraping_management.urls')),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Dashboard - Brand</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css'  %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i&amp;display=swap">
    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">

                    <div class="sidebar-brand-text mx-3 ">Sistema de <br> Web Scraping</div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item"><a class="nav-link active" href="index.html"><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'scraping_management:ejecuciones_list' %}"><i class="fas fa-user"></i><span>Ejecuciones</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'scraping_management:sitios_web_list' %}"><i class="fas fa-table"></i><span>Sitios Web</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'scraping_management:probar_parametros' %}"><i class="fas fa-tools"></i><span>Probar Parametros</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="register.html"><i class="fas fa-spider"></i><span>Gestionar Spider's</span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">


                    </div>
                </nav>
                <div class="container-fluid">
                    {% block content %}

                     {% endblock %}
                </div>
            </div>
            <footer class="bg-white sticky-footer">
<!--                <div class="container my-auto">-->
<!--                    <div class="text-center my-auto copyright"><span>Copyright © Brand 2022</span></div>-->
<!--                </div>-->
            </footer>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/chart.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-init.js' %}"></script>
    <script src="{% static 'assets/js/theme.js' %}"></script>
</body>

</html>